//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginTable1
    {
        public int custId { get; set; }
        public Nullable<int> Age { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string custName { get; set; }
        public string password { get; set; }
    }
}
